/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject9;

/**
 *
 * @author ERICA
 */
public class mainJFrame extends javax.swing.JFrame {
    private Machine machine;
    private Special special;
    private int totalPayment;

    /**
     * Creates new form mainJFrame
     */
    public mainJFrame(Machine machine, Special special) {
        this.machine = machine;
        this.special = special;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainMenuPanel = new javaproject9.MainMenuJPanel(machine, special);

        rvmMenuPanel = new javaproject9.RVMMenuJPanel(machine);
        svmMenuPanel = new javaproject9.SVMMenuJPanel(special);
        rvmPaymentPanel = new javaproject9.RVMPaymentPanel(machine);
        svmPaymentPanel = new javaproject9.SVMPaymentPanel(special);
        rvmMaintenancePanel = new javaproject9.RVMMaintenancePanel(machine);
        svmMaintenancePanel = new javaproject9.SVMMaintenancePanel(special);

        rvmPanel = new javaproject9.RVMPanel(machine, totalPayment);
        svmPanel = new javaproject9.SVMPanel(special, totalPayment);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(520, 487));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.CardLayout());

        jLayeredPane1.setLayout(new java.awt.CardLayout());
        jLayeredPane1.add(mainMenuPanel, "MainMenuPanel");
        jLayeredPane1.add(rvmPaymentPanel, "RVMPaymentPanel");
        jLayeredPane1.add(svmPaymentPanel, "SVMPaymentPanel");
        jLayeredPane1.add(rvmMenuPanel, "RVMMenuPanel");
        jLayeredPane1.add(svmMenuPanel, "SVMMenuPanel");
        jLayeredPane1.add(rvmMaintenancePanel, "RVMMaintenancePanel");
        jLayeredPane1.add(svmMaintenancePanel, "SVMMaintenancePanel");

        getContentPane().add(jLayeredPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public javax.swing.JLayeredPane getjLayeredPane1() {
        return jLayeredPane1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javaproject9.MainMenuJPanel mainMenuPanel;
    private javaproject9.RVMMaintenancePanel rvmMaintenancePanel;
    private javaproject9.SVMMaintenancePanel svmMaintenancePanel;
    private javaproject9.RVMMenuJPanel rvmMenuPanel;
    private javaproject9.SVMMenuJPanel svmMenuPanel;
    private javaproject9.RVMPanel rvmPanel;
    private javaproject9.SVMPanel svmPanel;
    private javaproject9.RVMPaymentPanel rvmPaymentPanel;
    private javaproject9.SVMPaymentPanel svmPaymentPanel;

    // End of variables declaration//GEN-END:variables
}
