/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject9;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author ERICA
 */
public class RVMCurrencyMaintenancePanel extends javax.swing.JPanel {

    private Machine machine;
    private RVMCurrencyOptionsPanel currencyPanel;
    private RVMPrintCurrencyPanel printCurrencyPanel;

    public RVMCurrencyMaintenancePanel(Machine machine) {
        this.machine = machine;
        initComponents();
        initializeCurrencyPanel(machine);
        initializePrintCurrencyPanel(machine);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        restockCurrencyButton = new javax.swing.JRadioButton();
        restockAllCurrencyButton = new javax.swing.JRadioButton();
        collectCurrencyButton = new javax.swing.JRadioButton();
        collectAllCurrencyButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        exitButton1 = new javax.swing.JButton();
        maintenanceSelectButton = new javax.swing.JButton();
        restockCurrencyPanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        container1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        exitButton2 = new javax.swing.JButton();
        restockConfirmButton = new javax.swing.JButton();
        restockCurrencyInput = new javax.swing.JTextField();
        restockCurrencyLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        restockAllCurrencyPanel = new javax.swing.JPanel();
        titleLabel2 = new javax.swing.JLabel();
        container2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        exitButton3 = new javax.swing.JButton();
        restockAllConfirmButton = new javax.swing.JButton();
        restockAllCurrencyInput = new javax.swing.JTextField();
        restockCurrencyLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        collectCurrencyPanel = new javax.swing.JPanel();
        titleLabel3 = new javax.swing.JLabel();
        container3 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        exitButton4 = new javax.swing.JButton();
        collectConfirmButton = new javax.swing.JButton();
        collectCurrencyInput = new javax.swing.JTextField();
        restockCurrencyLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        collectAllCurrencyPanel = new javax.swing.JPanel();
        titleLabel4 = new javax.swing.JLabel();
        container5 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        exitButton5 = new javax.swing.JButton();
        collectAllConfirmButton = new javax.swing.JButton();
        collectAllCurrencyInput = new javax.swing.JTextField();
        restockCurrencyLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        container4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(520, 470));
        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel.setText("CURRENCY MAINTENANCE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 276));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        restockCurrencyButton.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(restockCurrencyButton);
        restockCurrencyButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyButton.setForeground(new java.awt.Color(255, 153, 153));
        restockCurrencyButton.setText("Restock Currency");
        jPanel1.add(restockCurrencyButton);

        restockAllCurrencyButton.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(restockAllCurrencyButton);
        restockAllCurrencyButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockAllCurrencyButton.setForeground(new java.awt.Color(255, 153, 153));
        restockAllCurrencyButton.setText("Restock All Currency");
        jPanel1.add(restockAllCurrencyButton);

        collectCurrencyButton.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(collectCurrencyButton);
        collectCurrencyButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        collectCurrencyButton.setForeground(new java.awt.Color(255, 153, 153));
        collectCurrencyButton.setText("Collect Currency");
        jPanel1.add(collectCurrencyButton);

        collectAllCurrencyButton.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(collectAllCurrencyButton);
        collectAllCurrencyButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        collectAllCurrencyButton.setForeground(new java.awt.Color(255, 153, 153));
        collectAllCurrencyButton.setText("Collect All Currency");
        jPanel1.add(collectAllCurrencyButton);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        exitButton1.setBackground(new java.awt.Color(255, 153, 153));
        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        maintenanceSelectButton.setBackground(new java.awt.Color(153, 209, 153));
        maintenanceSelectButton.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        maintenanceSelectButton.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceSelectButton.setText("Select Option");
        maintenanceSelectButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        maintenanceSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(maintenanceSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(exitButton1))
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maintenanceSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(jPanel2, "card2");

        restockCurrencyPanel.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel1.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel1.setText("Vending Machine Maintenance");

        container1.setBackground(new java.awt.Color(255, 255, 204));
        container1.setPreferredSize(new java.awt.Dimension(500, 276));
        container1.setLayout(new java.awt.BorderLayout());

        jSeparator2.setForeground(new java.awt.Color(204, 204, 255));

        exitButton2.setBackground(new java.awt.Color(255, 153, 153));
        exitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });

        restockConfirmButton.setBackground(new java.awt.Color(153, 209, 153));
        restockConfirmButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        restockConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        restockConfirmButton.setText("Confirm");
        restockConfirmButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        restockConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockConfirmButtonActionPerformed(evt);
            }
        });

        restockCurrencyLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyLabel.setForeground(new java.awt.Color(255, 255, 204));
        restockCurrencyLabel.setText("RESTOCK CURRENCY");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Stock:");

        javax.swing.GroupLayout restockCurrencyPanelLayout = new javax.swing.GroupLayout(restockCurrencyPanel);
        restockCurrencyPanel.setLayout(restockCurrencyPanelLayout);
        restockCurrencyPanelLayout.setHorizontalGroup(
            restockCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restockCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockCurrencyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(restockCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(restockCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restockConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(exitButton2))
                    .addComponent(container1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(restockCurrencyPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(restockCurrencyLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        restockCurrencyPanelLayout.setVerticalGroup(
            restockCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restockCurrencyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(restockCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restockCurrencyPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(exitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(restockCurrencyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(restockCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restockCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restockConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(restockCurrencyPanel, "restockCurrencyPanel");

        restockAllCurrencyPanel.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel2.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel2.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel2.setText("Vending Machine Maintenance");

        container2.setBackground(new java.awt.Color(255, 255, 204));
        container2.setPreferredSize(new java.awt.Dimension(500, 276));
        container2.setLayout(new java.awt.BorderLayout());

        jSeparator3.setForeground(new java.awt.Color(204, 204, 255));

        exitButton3.setBackground(new java.awt.Color(255, 153, 153));
        exitButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton3ActionPerformed(evt);
            }
        });

        restockAllConfirmButton.setBackground(new java.awt.Color(153, 209, 153));
        restockAllConfirmButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        restockAllConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        restockAllConfirmButton.setText("Confirm");
        restockAllConfirmButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        restockAllConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockAllConfirmButtonActionPerformed(evt);
            }
        });

        restockCurrencyLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyLabel1.setForeground(new java.awt.Color(255, 255, 204));
        restockCurrencyLabel1.setText("RESTOCK ALL CURRENCY");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Stock:");

        javax.swing.GroupLayout restockAllCurrencyPanelLayout = new javax.swing.GroupLayout(restockAllCurrencyPanel);
        restockAllCurrencyPanel.setLayout(restockAllCurrencyPanelLayout);
        restockAllCurrencyPanelLayout.setHorizontalGroup(
            restockAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockAllCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restockAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockAllCurrencyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(restockAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(restockAllCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restockAllConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(exitButton3))
                    .addComponent(container2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockAllCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(restockAllCurrencyPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(restockCurrencyLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        restockAllCurrencyPanelLayout.setVerticalGroup(
            restockAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockAllCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restockCurrencyLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(restockAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restockAllCurrencyPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(exitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(restockAllCurrencyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(restockAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restockAllCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restockAllConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(restockAllCurrencyPanel, "restockAllCurrencyPanel");

        collectCurrencyPanel.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel3.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel3.setText("Vending Machine Maintenance");

        container3.setBackground(new java.awt.Color(255, 255, 204));
        container3.setPreferredSize(new java.awt.Dimension(500, 276));
        container3.setLayout(new java.awt.BorderLayout());

        jSeparator4.setForeground(new java.awt.Color(204, 204, 255));

        exitButton4.setBackground(new java.awt.Color(255, 153, 153));
        exitButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton4ActionPerformed(evt);
            }
        });

        collectConfirmButton.setBackground(new java.awt.Color(153, 209, 153));
        collectConfirmButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        collectConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        collectConfirmButton.setText("Confirm");
        collectConfirmButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        collectConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectConfirmButtonActionPerformed(evt);
            }
        });

        restockCurrencyLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyLabel2.setForeground(new java.awt.Color(255, 255, 204));
        restockCurrencyLabel2.setText("COLLECT CURRENCY");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Stock:");

        javax.swing.GroupLayout collectCurrencyPanelLayout = new javax.swing.GroupLayout(collectCurrencyPanel);
        collectCurrencyPanel.setLayout(collectCurrencyPanelLayout);
        collectCurrencyPanelLayout.setHorizontalGroup(
            collectCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collectCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collectCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collectCurrencyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(collectCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(collectCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collectConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(exitButton4))
                    .addComponent(container3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jSeparator4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collectCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(collectCurrencyPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(restockCurrencyLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        collectCurrencyPanelLayout.setVerticalGroup(
            collectCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collectCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restockCurrencyLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(collectCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(collectCurrencyPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(exitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(collectCurrencyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(collectCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(collectCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(collectConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(collectCurrencyPanel, "collectCurrencyPanel");

        collectAllCurrencyPanel.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel4.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel4.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel4.setText("Vending Machine Maintenance");

        container5.setBackground(new java.awt.Color(255, 255, 204));
        container5.setPreferredSize(new java.awt.Dimension(500, 276));
        container5.setLayout(new java.awt.BorderLayout());

        jSeparator5.setForeground(new java.awt.Color(204, 204, 255));

        exitButton5.setBackground(new java.awt.Color(255, 153, 153));
        exitButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton5ActionPerformed(evt);
            }
        });

        collectAllConfirmButton.setBackground(new java.awt.Color(153, 209, 153));
        collectAllConfirmButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        collectAllConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        collectAllConfirmButton.setText("Confirm");
        collectAllConfirmButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        collectAllConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectAllConfirmButtonActionPerformed(evt);
            }
        });

        restockCurrencyLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyLabel3.setForeground(new java.awt.Color(255, 255, 204));
        restockCurrencyLabel3.setText("COLLECT ALL CURRENCY");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Stock:");

        javax.swing.GroupLayout collectAllCurrencyPanelLayout = new javax.swing.GroupLayout(collectAllCurrencyPanel);
        collectAllCurrencyPanel.setLayout(collectAllCurrencyPanelLayout);
        collectAllCurrencyPanelLayout.setHorizontalGroup(
            collectAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collectAllCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collectAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collectAllCurrencyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(collectAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(collectAllCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collectAllConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(exitButton5))
                    .addComponent(container5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jSeparator5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collectAllCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(collectAllCurrencyPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(restockCurrencyLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        collectAllCurrencyPanelLayout.setVerticalGroup(
            collectAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collectAllCurrencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restockCurrencyLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(collectAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(collectAllCurrencyPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(exitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(collectAllCurrencyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(collectAllCurrencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(collectAllCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(collectAllConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(collectAllCurrencyPanel, "collectAllCurrencyPanel");

        container4.setBackground(new java.awt.Color(255, 255, 204));
        container4.setPreferredSize(new java.awt.Dimension(500, 276));
        container4.setLayout(new java.awt.BorderLayout());
        add(container4, "card6");
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearButtonActionPerformed
        buttonGroup1.clearSelection();
    }// GEN-LAST:event_clearButtonActionPerformed

    private void maintenanceSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maintenanceSelectButtonActionPerformed

        if (!restockCurrencyButton.isSelected()
                && !restockAllCurrencyButton.isSelected()
                && !collectCurrencyButton.isSelected()
                && !collectAllCurrencyButton.isSelected()) {

            JOptionPane.showMessageDialog(this, "Please select an option before proceeding.", "Option Not Selected",
                    JOptionPane.ERROR_MESSAGE);

        }
        if (restockCurrencyButton.isSelected()) {
            CardLayout cardLayout = (CardLayout) getLayout();
            cardLayout.show(this, "restockCurrencyPanel");
            container1.add(currencyPanel, BorderLayout.CENTER);

        } else if (restockAllCurrencyButton.isSelected()) {
            CardLayout cardLayout = (CardLayout) getLayout();
            cardLayout.show(this, "restockAllCurrencyPanel");
            container2.add(printCurrencyPanel, BorderLayout.CENTER);

        } else if (collectCurrencyButton.isSelected()) {
            CardLayout cardLayout = (CardLayout) getLayout();
            cardLayout.show(this, "collectCurrencyPanel");
            container3.add(currencyPanel, BorderLayout.CENTER);

        } else if (collectAllCurrencyButton.isSelected()) {
            CardLayout cardLayout = (CardLayout) getLayout();
            cardLayout.show(this, "collectAllCurrencyPanel");
            container5.add(printCurrencyPanel, BorderLayout.CENTER);
        }

        jPanel1.revalidate();
        jPanel1.repaint();

    }// GEN-LAST:event_maintenanceSelectButtonActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton1ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RVMMaintenancePanel maintenancePanel = new RVMMaintenancePanel(machine);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(maintenancePanel, "maintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "maintenancePanel");
    }// GEN-LAST:event_exitButton1ActionPerformed

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton2ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RVMCurrencyMaintenancePanel productMaintenancePanel = new RVMCurrencyMaintenancePanel(machine);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(productMaintenancePanel, "productMaintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "productMaintenancePanel");
    }// GEN-LAST:event_exitButton2ActionPerformed

    private void restockConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_restockConfirmButtonActionPerformed
RVMCurrencyOptionsPanel currencyPanel = (RVMCurrencyOptionsPanel) container1.getComponent(0);
        String selectedCurrencyString = currencyPanel.getSelectedCurrency();
        try {
            int selectedCurrency = Integer.parseInt(selectedCurrencyString);
            if (selectedCurrency >= 0) {
                String userInput = restockCurrencyInput.getText().trim();

                int inputAmount = Integer.parseInt(userInput);

                if (inputAmount > 0) {
                    performCurrencyRestock(selectedCurrency, inputAmount);
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid restock amount.",
                            "Invalid Input", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a currency value before making a restock.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input.",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_restockConfirmButtonActionPerformed

    private void exitButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton3ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RVMCurrencyMaintenancePanel productMaintenancePanel = new RVMCurrencyMaintenancePanel(machine);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(productMaintenancePanel, "productMaintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "productMaintenancePanel");
    }// GEN-LAST:event_exitButton3ActionPerformed

    private void restockAllConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_restockAllConfirmButtonActionPerformed
                String userInput = restockAllCurrencyInput.getText().trim();

        try {
            if (userInput != null) {
                int inputAmount = Integer.parseInt(userInput);

                if (inputAmount > 0) {
                    performAllCurrencyRestock(inputAmount);
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid restock amount.", "Invalid Input",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid quantity.", "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_restockAllConfirmButtonActionPerformed

    private void exitButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton4ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RVMCurrencyMaintenancePanel productMaintenancePanel = new RVMCurrencyMaintenancePanel(machine);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(productMaintenancePanel, "productMaintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "productMaintenancePanel");
    }// GEN-LAST:event_exitButton4ActionPerformed

    private void collectConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_collectConfirmButtonActionPerformed
        RVMCurrencyOptionsPanel currencyPanel = (RVMCurrencyOptionsPanel) container3.getComponent(0);
        String selectedCurrencyString = currencyPanel.getSelectedCurrency();

        try {
            int selectedCurrency = Integer.parseInt(selectedCurrencyString);

            if (selectedCurrency >= 0) {
                String userInput = collectCurrencyInput.getText().trim();

                int inputAmount = Integer.parseInt(userInput);

                if (inputAmount > 0) {
                    performCurrencyCollect(selectedCurrency, inputAmount);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.",
                            "Invalid Input", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a currency value before collecting.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid selected currency. Please select a valid currency value.", "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_collectConfirmButtonActionPerformed

    private void exitButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton5ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        RVMCurrencyMaintenancePanel productMaintenancePanel = new RVMCurrencyMaintenancePanel(machine);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(productMaintenancePanel, "productMaintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "productMaintenancePanel");
    }// GEN-LAST:event_exitButton5ActionPerformed

    private void collectAllConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_collectAllConfirmButtonActionPerformed
        String userInput = collectAllCurrencyInput.getText().trim();

        try {
            int inputAmount = Integer.parseInt(userInput);

            if (inputAmount > 0) {
                performAllCurrencyCollect(inputAmount);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Input",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_collectAllConfirmButtonActionPerformed

    private void performCurrencyRestock(int currencyValue, int inputAmount) {

        try {
           
            if (machine.isValidCurrencyValue(currencyValue)) {
                machine.restockCurrency(currencyValue, inputAmount);
                container1.removeAll();
                initializeCurrencyPanel(machine);
                container1.add(currencyPanel, BorderLayout.CENTER);
                restockCurrencyInput.setText("");
            } else {

                JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Stock",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void performAllCurrencyRestock(int inputAmount) {

        try {
            machine.restockAllCurrency(inputAmount);
            container2.removeAll();
            initializePrintCurrencyPanel(machine);
            container2.add(printCurrencyPanel, BorderLayout.CENTER);
            restockAllCurrencyInput.setText("");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Stock",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void performCurrencyCollect(int currencyValue, int inputAmount) {

       try {
            if (inputAmount > 0) {
                machine.collectCurrency(currencyValue, inputAmount);
                container3.removeAll();
                initializeCurrencyPanel(machine);
                container3.add(currencyPanel, BorderLayout.CENTER);
                collectCurrencyInput.setText("");
            } else {

                JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Stock",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void performAllCurrencyCollect(int inputAmount) {

        try {
            machine.collectAllCurrency(inputAmount);
            container5.removeAll();
            initializePrintCurrencyPanel(machine);
            container5.add(printCurrencyPanel, BorderLayout.CENTER);
            collectAllCurrencyInput.setText("");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Stock",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initializeCurrencyPanel(Machine machine) {
        if (currencyPanel != null) {
            container4.removeAll();
        }
        currencyPanel = new RVMCurrencyOptionsPanel(machine);

        container4.add(currencyPanel, BorderLayout.CENTER);

        container4.revalidate();
        container4.repaint();
    }

    private void initializePrintCurrencyPanel(Machine machine) {
        if (printCurrencyPanel != null) {
            container4.removeAll();
        }

        printCurrencyPanel = new RVMPrintCurrencyPanel(machine);

        container4.add(printCurrencyPanel, BorderLayout.CENTER);

        container4.revalidate();
        container4.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton collectAllConfirmButton;
    private javax.swing.JRadioButton collectAllCurrencyButton;
    private javax.swing.JTextField collectAllCurrencyInput;
    private javax.swing.JPanel collectAllCurrencyPanel;
    private javax.swing.JButton collectConfirmButton;
    private javax.swing.JRadioButton collectCurrencyButton;
    private javax.swing.JTextField collectCurrencyInput;
    private javax.swing.JPanel collectCurrencyPanel;
    private javax.swing.JPanel container1;
    private javax.swing.JPanel container2;
    private javax.swing.JPanel container3;
    private javax.swing.JPanel container4;
    private javax.swing.JPanel container5;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton exitButton2;
    private javax.swing.JButton exitButton3;
    private javax.swing.JButton exitButton4;
    private javax.swing.JButton exitButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton maintenanceSelectButton;
    private javax.swing.JButton restockAllConfirmButton;
    private javax.swing.JRadioButton restockAllCurrencyButton;
    private javax.swing.JTextField restockAllCurrencyInput;
    private javax.swing.JPanel restockAllCurrencyPanel;
    private javax.swing.JButton restockConfirmButton;
    private javax.swing.JRadioButton restockCurrencyButton;
    private javax.swing.JTextField restockCurrencyInput;
    private javax.swing.JLabel restockCurrencyLabel;
    private javax.swing.JLabel restockCurrencyLabel1;
    private javax.swing.JLabel restockCurrencyLabel2;
    private javax.swing.JLabel restockCurrencyLabel3;
    private javax.swing.JPanel restockCurrencyPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    private javax.swing.JLabel titleLabel4;
    // End of variables declaration//GEN-END:variables
}
