/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject9;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ERICA
 */
public class SVMPanel extends javax.swing.JPanel {

    private Special special;
    private int totalPayment;
    private int change;
    private SVMProductsPanel svmProductsPanel;

    /**
     * Creates new form MainMenuJPanel
     */
    public SVMPanel(Special special, int totalPayment) {
        this.special = special;
        this.totalPayment = totalPayment;
        initComponents();
        initializeComboProductsPanel(special);
        svmChangeButton.setVisible(false);
        updatePaymentLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        svmChangeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        svmPurchaseButton = new javax.swing.JButton();
        paymentLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(482, 470));

        titleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel.setText("FROYO VENDING MACHINE");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        svmChangeButton.setBackground(new java.awt.Color(209, 235, 209));
        svmChangeButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        svmChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        svmChangeButton.setText("Dispense Change");
        svmChangeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        svmChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmChangeButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        svmPurchaseButton.setBackground(new java.awt.Color(209, 235, 209));
        svmPurchaseButton.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        svmPurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        svmPurchaseButton.setText("Purchase");
        svmPurchaseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        svmPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmPurchaseButtonActionPerformed(evt);
            }
        });

        paymentLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentLabel.setText("Total Payment:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(svmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(svmPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(svmPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(svmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void svmChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_svmChangeButtonActionPerformed
        String changeString = special.dispenseChange(change);

        special.updateCurrencyStockWithChange(special.calculateChangeQuantity(change));

        JOptionPane.showMessageDialog(this, "Change is " + changeString + "\n" + " = PHP" + change);
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "SVMMenuPanel");

    }// GEN-LAST:event_svmChangeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        String changeDenominations = special.dispenseChange(totalPayment);
        special.updateCurrencyStockWithChange(special.calculateChangeQuantity(totalPayment));
        JOptionPane.showMessageDialog(this, "Payment returned: PHP " + changeDenominations + " = PHP " + totalPayment);

        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "SVMMenuPanel");
    }// GEN-LAST:event_jButton1ActionPerformed

    private void svmPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_svmPurchaseButtonActionPerformed

        SVMProductsPanel svmProductsPanel = (SVMProductsPanel) jPanel1.getComponent(0);
        ArrayList<Product> selectedComboProducts = svmProductsPanel.getSelectedComboProducts();
        if (special.yogurtAvailability()) {
            Combo combo = special.generateCombo(selectedComboProducts);
            int price = combo.getPrice();
            if (special.isValidPayment(price, totalPayment)) {
                if (selectedComboProducts.size() > 1) {
                    change = special.calculateTotalChange(price, totalPayment);

                    boolean status = special.performPurchase(combo, totalPayment);

                    if (status) {
                        initializeComboProductsPanel(special);
                        totalPayment = change;
                        updatePaymentLabel();
                        svmChangeButton.setVisible(true);
                        jButton1.setVisible(false);
                        String message = special.preparingCombo(combo);
                        JOptionPane.showMessageDialog(this, message + "\nChange: " + change);

                    } else {

                        JOptionPane.showMessageDialog(this, "Insufficient change in machine.", "Transaction failed",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Please select a product. ", "Invalid Selection",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Payment is invalid.", "Invalid Payment",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Yogurt not available.",
                    "Out of Stock ", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_svmPurchaseButtonActionPerformed

    private void initializeComboProductsPanel(Special special) {
        if (svmProductsPanel != null) {
            jPanel1.remove(svmProductsPanel);
        }

        svmProductsPanel = new SVMProductsPanel(special);

        jPanel1.add(svmProductsPanel, BorderLayout.CENTER);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void updatePaymentLabel() {

        paymentLabel.setText("Total Payment: PHP " + totalPayment);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JButton svmChangeButton;
    private javax.swing.JButton svmPurchaseButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
