/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject9;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author ERICA
 */
public class SVMProductMaintenancePanel extends javax.swing.JPanel {

    private Special special;
    private SVMProductOptionsPanel productsPanel;
    private SVMPrintProductPanel printProductPanel;

    public SVMProductMaintenancePanel(Special special) {
        this.special = special;
        initComponents();
        initializeProductsPanel(special);
        initializePrintProductPanel(special);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        restockSlotButton = new javax.swing.JRadioButton();
        restockAllSlotsButton = new javax.swing.JRadioButton();
        editPriceButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        exitButton1 = new javax.swing.JButton();
        maintenanceSelectButton = new javax.swing.JButton();
        restockSlotPanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        container1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        exitButton2 = new javax.swing.JButton();
        confirmRestockSlotButton = new javax.swing.JButton();
        restockSlotInput = new javax.swing.JTextField();
        restockCurrencyLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        restockAllSlotsPanel = new javax.swing.JPanel();
        titleLabel2 = new javax.swing.JLabel();
        container2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        exitButton3 = new javax.swing.JButton();
        confirmRestockAllButton = new javax.swing.JButton();
        restockAllInput = new javax.swing.JTextField();
        restockCurrencyLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editPricePanel = new javax.swing.JPanel();
        titleLabel3 = new javax.swing.JLabel();
        container3 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        exitButton4 = new javax.swing.JButton();
        confirmEditPriceButton = new javax.swing.JButton();
        editPriceInput = new javax.swing.JTextField();
        restockCurrencyLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        container4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(520, 470));
        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel.setText("PRODUCT MAINTENANCE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 276));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        restockSlotButton.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(restockSlotButton);
        restockSlotButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockSlotButton.setForeground(new java.awt.Color(255, 153, 153));
        restockSlotButton.setText("Restock Product");
        jPanel1.add(restockSlotButton);

        restockAllSlotsButton.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(restockAllSlotsButton);
        restockAllSlotsButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockAllSlotsButton.setForeground(new java.awt.Color(255, 153, 153));
        restockAllSlotsButton.setText("Restock All Slot");
        jPanel1.add(restockAllSlotsButton);

        editPriceButton.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(editPriceButton);
        editPriceButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        editPriceButton.setForeground(new java.awt.Color(255, 153, 153));
        editPriceButton.setText("Edit Product Price");
        jPanel1.add(editPriceButton);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        exitButton1.setBackground(new java.awt.Color(255, 153, 153));
        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        maintenanceSelectButton.setBackground(new java.awt.Color(153, 209, 153));
        maintenanceSelectButton.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        maintenanceSelectButton.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceSelectButton.setText("Select Option");
        maintenanceSelectButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        maintenanceSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(maintenanceSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(exitButton1))
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maintenanceSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(jPanel2, "card2");

        restockSlotPanel.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel1.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel1.setText("Vending Machine Maintenance");

        container1.setBackground(new java.awt.Color(255, 255, 204));
        container1.setPreferredSize(new java.awt.Dimension(500, 276));
        container1.setLayout(new java.awt.BorderLayout());

        jSeparator2.setForeground(new java.awt.Color(204, 204, 255));

        exitButton2.setBackground(new java.awt.Color(255, 153, 153));
        exitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });

        confirmRestockSlotButton.setBackground(new java.awt.Color(153, 209, 153));
        confirmRestockSlotButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        confirmRestockSlotButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmRestockSlotButton.setText("Confirm");
        confirmRestockSlotButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        confirmRestockSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRestockSlotButtonActionPerformed(evt);
            }
        });

        restockCurrencyLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyLabel.setForeground(new java.awt.Color(255, 255, 204));
        restockCurrencyLabel.setText("RESTOCK SLOT");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Stock:");

        javax.swing.GroupLayout restockSlotPanelLayout = new javax.swing.GroupLayout(restockSlotPanel);
        restockSlotPanel.setLayout(restockSlotPanelLayout);
        restockSlotPanelLayout.setHorizontalGroup(
            restockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockSlotPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockSlotPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(restockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(restockSlotInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmRestockSlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(exitButton2))
                    .addComponent(container1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockSlotPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(restockSlotPanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(restockCurrencyLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        restockSlotPanelLayout.setVerticalGroup(
            restockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockSlotPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restockCurrencyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(restockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restockSlotPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(exitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(restockSlotPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(restockSlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restockSlotInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmRestockSlotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(restockSlotPanel, "restockSlotPanel");

        restockAllSlotsPanel.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel2.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel2.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel2.setText("Vending Machine Maintenance");

        container2.setBackground(new java.awt.Color(255, 255, 204));
        container2.setPreferredSize(new java.awt.Dimension(500, 276));
        container2.setLayout(new java.awt.BorderLayout());

        jSeparator3.setForeground(new java.awt.Color(204, 204, 255));

        exitButton3.setBackground(new java.awt.Color(255, 153, 153));
        exitButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton3ActionPerformed(evt);
            }
        });

        confirmRestockAllButton.setBackground(new java.awt.Color(153, 209, 153));
        confirmRestockAllButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        confirmRestockAllButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmRestockAllButton.setText("Confirm");
        confirmRestockAllButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        confirmRestockAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRestockAllButtonActionPerformed(evt);
            }
        });

        restockCurrencyLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyLabel1.setForeground(new java.awt.Color(255, 255, 204));
        restockCurrencyLabel1.setText("RESTOCK ALL SLOTS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Stock:");

        javax.swing.GroupLayout restockAllSlotsPanelLayout = new javax.swing.GroupLayout(restockAllSlotsPanel);
        restockAllSlotsPanel.setLayout(restockAllSlotsPanelLayout);
        restockAllSlotsPanelLayout.setHorizontalGroup(
            restockAllSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockAllSlotsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restockAllSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockAllSlotsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(restockAllSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(restockAllInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmRestockAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(exitButton3))
                    .addComponent(container2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockAllSlotsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(restockAllSlotsPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(restockCurrencyLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        restockAllSlotsPanelLayout.setVerticalGroup(
            restockAllSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockAllSlotsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restockCurrencyLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(restockAllSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restockAllSlotsPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(exitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(restockAllSlotsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(restockAllSlotsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restockAllInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmRestockAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(restockAllSlotsPanel, "restockAllSlotsPanel");

        editPricePanel.setBackground(new java.awt.Color(255, 204, 204));

        titleLabel3.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel3.setText("Vending Machine Maintenance");

        container3.setBackground(new java.awt.Color(255, 255, 204));
        container3.setPreferredSize(new java.awt.Dimension(500, 276));
        container3.setLayout(new java.awt.BorderLayout());

        jSeparator4.setForeground(new java.awt.Color(204, 204, 255));

        exitButton4.setBackground(new java.awt.Color(255, 153, 153));
        exitButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton4ActionPerformed(evt);
            }
        });

        confirmEditPriceButton.setBackground(new java.awt.Color(153, 209, 153));
        confirmEditPriceButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        confirmEditPriceButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmEditPriceButton.setText("Confirm");
        confirmEditPriceButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        confirmEditPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEditPriceButtonActionPerformed(evt);
            }
        });

        editPriceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPriceInputActionPerformed(evt);
            }
        });

        restockCurrencyLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        restockCurrencyLabel2.setForeground(new java.awt.Color(255, 255, 204));
        restockCurrencyLabel2.setText("EDIT PRODUCT PRICE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter price:");

        javax.swing.GroupLayout editPricePanelLayout = new javax.swing.GroupLayout(editPricePanel);
        editPricePanel.setLayout(editPricePanelLayout);
        editPricePanelLayout.setHorizontalGroup(
            editPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPricePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(editPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmEditPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(exitButton4))
                    .addComponent(container3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jSeparator4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPricePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(editPricePanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(restockCurrencyLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editPricePanelLayout.setVerticalGroup(
            editPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restockCurrencyLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(editPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPricePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(exitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPricePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmEditPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(editPricePanel, "editPricePanel");

        container4.setBackground(new java.awt.Color(255, 255, 204));
        container4.setPreferredSize(new java.awt.Dimension(500, 276));
        container4.setLayout(new java.awt.BorderLayout());
        add(container4, "card6");
    }// </editor-fold>//GEN-END:initComponents

    private void editPriceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPriceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPriceInputActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearButtonActionPerformed
        buttonGroup1.clearSelection();
    }// GEN-LAST:event_clearButtonActionPerformed

    private void maintenanceSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_maintenanceSelectButtonActionPerformed

        if (!restockSlotButton.isSelected()
                && !restockAllSlotsButton.isSelected()
                && !editPriceButton.isSelected()) {

            JOptionPane.showMessageDialog(this, "Please select an option before proceeding.", "Option Not Selected",
                    JOptionPane.ERROR_MESSAGE);

        }

        if (restockSlotButton.isSelected()) {
            CardLayout cardLayout = (CardLayout) getLayout();
            cardLayout.show(this, "restockSlotPanel");
            container1.add(productsPanel, BorderLayout.CENTER);

        } else if (restockAllSlotsButton.isSelected()) {
            CardLayout cardLayout = (CardLayout) getLayout();
            cardLayout.show(this, "restockAllSlotsPanel");
            container2.add(printProductPanel, BorderLayout.CENTER);

        } else if (editPriceButton.isSelected()) {
            CardLayout cardLayout = (CardLayout) getLayout();
            cardLayout.show(this, "editPricePanel");
            container3.add(productsPanel, BorderLayout.CENTER);
        }

        jPanel1.revalidate();
        jPanel1.repaint();

    }// GEN-LAST:event_maintenanceSelectButtonActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton1ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        SVMMaintenancePanel maintenancePanel = new SVMMaintenancePanel(special);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(maintenancePanel, "maintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "maintenancePanel");
    }// GEN-LAST:event_exitButton1ActionPerformed

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton2ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        SVMProductMaintenancePanel productMaintenancePanel = new SVMProductMaintenancePanel(special);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(productMaintenancePanel, "productMaintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "productMaintenancePanel");
    }// GEN-LAST:event_exitButton2ActionPerformed

    private void confirmRestockSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmButton1ActionPerformed

        SVMProductOptionsPanel productsPanel = (SVMProductOptionsPanel) container1.getComponent(0);
        String selectedProduct = productsPanel.getSelectedProduct();

        try {
            if (selectedProduct != null) {
                String userInput = restockSlotInput.getText().trim();

                int inputAmount = Integer.parseInt(userInput);

                if (inputAmount > 0) {
                    performRestock(selectedProduct, inputAmount);
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid restock amount.",
                            "Invalid Input", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a product before restocking.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input.",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_confirmButton1ActionPerformed

    private void exitButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton3ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        SVMProductMaintenancePanel productMaintenancePanel = new SVMProductMaintenancePanel(special);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(productMaintenancePanel, "productMaintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "productMaintenancePanel");
    }// GEN-LAST:event_exitButton3ActionPerformed

    private void confirmRestockAllButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmButton2ActionPerformed
        String userInput = restockAllInput.getText().trim();
        try {
            if (userInput != null) {
                int inputAmount = Integer.parseInt(userInput);

                if (inputAmount > 0) {

                    performAllRestock(inputAmount);

                } else {
                    JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid quantity.", "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_confirmButton2ActionPerformed

    private void exitButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButton4ActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        SVMProductMaintenancePanel productMaintenancePanel = new SVMProductMaintenancePanel(special);

        javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        jLayeredPane1.add(productMaintenancePanel, "productMaintenancePanel");

        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "productMaintenancePanel");
    }// GEN-LAST:event_exitButton4ActionPerformed

    private void confirmEditPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmButton3ActionPerformed
        SVMProductOptionsPanel productsPanel = (SVMProductOptionsPanel) container3.getComponent(0);
        String selectedProduct = productsPanel.getSelectedProduct();

        try {
            if (selectedProduct != null) {
                String userInput = editPriceInput.getText().trim();

                int inputAmount = Integer.parseInt(userInput);

                if (inputAmount >= 0) {

                    performEditPrice(selectedProduct, inputAmount);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid price. Please enter a valid quantity.",
                            "Invalid Price", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Input",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Price",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_confirmButton3ActionPerformed

    private void performRestock(String selectedProduct, int stock) {
        int slotIndex = special.findSlotIndexByProduct(selectedProduct);
        try {
            if (special.validRestock(stock)) {
                special.restockSlot(slotIndex, stock);
                special.clearTransactionList();
                container1.removeAll();
                initializeProductsPanel(special);
                container1.add(productsPanel, BorderLayout.CENTER);
                restockSlotInput.setText("");
            } else {

                JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Stock",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void performAllRestock(int inputAmount) {

        try {
            int stock = inputAmount;
            if (special.validRestockAll(stock)) {
                special.restockAllSlots(stock);
                special.clearTransactionList();
                container2.removeAll();
                initializePrintProductPanel(special);
                container2.add(printProductPanel, BorderLayout.CENTER);
                restockAllInput.setText("");
            } else {

                JOptionPane.showMessageDialog(this, "Invalid stock. Please enter a valid quantity.", "Invalid Stock",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Stock",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void performEditPrice(String selectedProduct, int newPrice) {

        int slotIndex = special.findSlotIndexByProduct(selectedProduct);
        try {
            special.editPrice(slotIndex, newPrice);
            container3.removeAll();
            initializeProductsPanel(special);
            container3.add(productsPanel, BorderLayout.CENTER);
            editPriceInput.setText("");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Invalid input. Please enter an integer.", "Invalid Price",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initializeProductsPanel(Special special) {
        if (productsPanel != null) {
            container4.removeAll();
        }

        productsPanel = new SVMProductOptionsPanel(special);

        container4.add(productsPanel, BorderLayout.CENTER);

        container4.revalidate();
        container4.repaint();
    }

    private void initializePrintProductPanel(Special special) {
        if (printProductPanel != null) {
            container4.removeAll();
        }

        printProductPanel = new SVMPrintProductPanel(special);

        container4.add(printProductPanel, BorderLayout.CENTER);

        container4.revalidate();
        container4.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmEditPriceButton;
    private javax.swing.JButton confirmRestockAllButton;
    private javax.swing.JButton confirmRestockSlotButton;
    private javax.swing.JPanel container1;
    private javax.swing.JPanel container2;
    private javax.swing.JPanel container3;
    private javax.swing.JPanel container4;
    private javax.swing.JRadioButton editPriceButton;
    private javax.swing.JTextField editPriceInput;
    private javax.swing.JPanel editPricePanel;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton exitButton2;
    private javax.swing.JButton exitButton3;
    private javax.swing.JButton exitButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton maintenanceSelectButton;
    private javax.swing.JTextField restockAllInput;
    private javax.swing.JRadioButton restockAllSlotsButton;
    private javax.swing.JPanel restockAllSlotsPanel;
    private javax.swing.JLabel restockCurrencyLabel;
    private javax.swing.JLabel restockCurrencyLabel1;
    private javax.swing.JLabel restockCurrencyLabel2;
    private javax.swing.JRadioButton restockSlotButton;
    private javax.swing.JTextField restockSlotInput;
    private javax.swing.JPanel restockSlotPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    // End of variables declaration//GEN-END:variables
}
