/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject9;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author ERICA
 */
public class SVMProductOptionsPanel extends javax.swing.JPanel {

    private Special special;

    /**
     * Creates new form ProductsPanel
     *
     * @param special
     */
    public SVMProductOptionsPanel(Special special) {
        this.special = special;
        initComponents();
        generateProductButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE));
    }// </editor-fold>

    private void generateProductButtons() {
        ArrayList<Slot> slotList = special.getSlotList();
        buttonGroup1 = new ButtonGroup();

        removeAll();

        int y = 10;

        for (Slot slot : slotList) {
            JRadioButton radioButton = new JRadioButton(slot.getProduct().getName());
            radioButton.setActionCommand(slot.getProduct().getName());
            buttonGroup1.add(radioButton);

            radioButton.setBackground(null);

            JLabel stockLabel = new JLabel("Stock: " + slot.getStock());
            JLabel priceLabel = new JLabel("Price: PHP " + slot.getProduct().getPrice());
            JLabel caloriesLabel = new JLabel("Calories: " + slot.getProduct().getCalories());

            radioButton.setBounds(10, y, 100, 20);
            stockLabel.setBounds(120, y, 100, 20);
            priceLabel.setBounds(230, y, 150, 20);
            caloriesLabel.setBounds(390, y, 150, 20);

            y += 30;

            add(radioButton);
            add(stockLabel);
            add(priceLabel);
            add(caloriesLabel);

        }

        int preferredHeight = y + 10;
        setPreferredSize(new Dimension(getPreferredSize().width, preferredHeight));

        revalidate();
        repaint();
    }

    public String getSelectedProduct() {
        ButtonModel selectedButton = buttonGroup1.getSelection();

        if (selectedButton != null) {
            return selectedButton.getActionCommand();
        }

        return null;
    }

    public void clearSelection() {
        buttonGroup1.clearSelection();
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}
